services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    env_file:
      - .env.docker
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  indexer:
    build: ./backend
    command: node indexer.js
    env_file:
      - .env.docker
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data: